tfc_webapps/defensa/urls.py
from django.conf.urls.defaults import *
from django.core.urlresolvers import reverse
from django.views.defaults import page_not_found

from defensa import models

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('defensa.views',
    url(r'^/$', 'index'),
    url(r'^/titulacion/find-by-centro/$', 'filter', {
        'model_class': models.Titulacion,
        'field_name': 'centro',
        'order_by': ('nombre', '-anyo_comienzo_plan'),
    }),
    url(r'^/solicitar/$', 'solicitar_defensa'),
    url(r'^/(?P<id>\d+)/$', 'solicitud_mostrar', name='trabajo_view'),
    url(r'^/(?P<id>\d+)/contenido/$', 'descargar_trabajo'),
    url(r'^/(?P<id>\d+)/editar/$', 'editar_trabajo'),
    url(r'^/(?P<id>\d+)/anexo/(?P<anexo_id>\d+)/$', page_not_found, name='anexo_view'),
    url(r'^/(?P<id>\d+)/anexo/(?P<anexo_id>\d+)/contenido/$', 'descargar_anexo'),
    url(r'^/(?P<id>\d+)/anexo/(?P<anexo_id>\d+)/editar/$', 'editar_anexo'),
    url(r'^/(?P<id>\d+)/autorizar/$', 'autorizar_defensa'),
    url(r'^/(?P<id>\d+)/autorizacion/$', 'descargar_autorizacion'),
    url(r'^/(?P<id>\d+)/calificar/$', 'calificar_trabajo'),
    url(r'^/(?P<id>\d+)/archivar/$', 'archivar_trabajo'),
    url(r'^/autorizar/$', 'lista_autorizar'),
    url(r'^/calificar/$', 'lista_calificar'),
    url(r'^/archivar/$', 'lista_archivar'),
)

tfc_webapps/urls.py
from django.conf.urls.defaults import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import login, logout
from django.views.generic.simple import redirect_to

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tfc_webapps.views.home', name='home'),
    # url(r'^tfc_webapps/', include('tfc_webapps.foo.urls')),
    url(r'^$', redirect_to, {'url': '/defensa/'}),
    url(r'^accounts/login/$', login, {'template_name': 'login.html'}),
    url(r'^accounts/logout/$', logout, {'next_page': '/'}),
    url(r'^defensa', include('defensa.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

tfc_webapps/defensa/models.py
# -*- coding: utf-8 -*-
#  Gestión de Trabajos Fin de Carrera de la Universidad de La Laguna
#
#    Copyright (C) 2011-2012 Pedro Cabrera <pdrcabrod@gmail.com>
#                            Jesús Torres  <jmtorres@ull.es>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from django.core.files.uploadedfile import UploadedFile
from django.core.validators import MaxLengthValidator
from django.db import models, transaction
from django.contrib import auth
from django.utils import formats

from defensa import settings, validators
from defensa.alfresco import Alfresco

import os
import re
import tempfile
import urllib


class AlfrescoPFCModel(models.Model):
    """Modelo abstracto base de todos los modelos cuyos datos se exportal a Alfresco."""

    NAMESPACES = Alfresco.NAMESPACES
    NAMESPACES['pfc'] = settings.ALFRESCO_PFC_MODEL_NAMESPACE 

    class Meta:
        abstract = True

    @classmethod
    def resolve_alfresco_prefixes(cls, properties):
        items = list(properties.items())
        for i, item in enumerate(items):
            (namespace, sep, name) = item[0].partition(':')
            if sep and namespace in cls.NAMESPACES:
                items[i] = (cls.NAMESPACES[namespace] % name, item[1])
        return dict(items)

    def get_alfresco_properties(self):
        self.alfresco_properties = self._get_alfresco_properties()
        return self.alfresco_properties

    def _get_alfresco_properties(self):
        return {}


class Centro(AlfrescoPFCModel):
    """Modelo de los centros."""
    
    nombre = models.CharField(max_length=200)
    codigo_centro = models.CharField(max_length=200)
    alfresco_uuid = models.CharField(max_length=36, blank = 'true', null = 'true', validators=[validators.UUIDValidator])

    def __unicode__(self):
        return self.nombre

    def _get_alfresco_properties(self):
        return {
            'cm:name': self.nombre,
	    'pfc:codigoCentro' : self.codigo_centro,
        }


class Titulacion(AlfrescoPFCModel):
    """Modelo de las titulaciones."""

    nombre = models.CharField(max_length=200)
    centro = models.ForeignKey(Centro)
    codigo_plan = models.CharField(max_length=200)
    anyo_comienzo_plan = models.IntegerField()
    titulacion_vigente = models.BooleanField()
    alfresco_uuid = models.CharField(max_length=36, blank = 'true', null = 'true', validators=[validators.UUIDValidator])

    def __unicode__(self):
        return "%s (Plan %4d)" % (self.nombre, self.anyo_comienzo_plan)

    def _get_alfresco_properties(self):
        return {
            'cm:name': self.nombre,
	    'pfc:codigoPlan' : self.codigo_plan,
	    'pfc:anyoComienzoPlan' : self.anyo_comienzo_plan,
	    'pfc:titulacionVigente' : self.titulacion_vigente
        }    


class Contenido(AlfrescoPFCModel):
    """Modelo base para todos los tipos de contenidos almacenados en el repositorio."""
    
    # campos dublin core
    title = models.CharField(max_length=200, verbose_name="título")
    format = models.CharField(max_length=30, choices=settings.FORMATO_SELECCION)
    description = models.TextField(verbose_name="descripción", validators=[MaxLengthValidator(1000)])
    language = models.CharField(max_length=2, choices=settings.LENGUAJE_SELECCION, verbose_name="idioma", default=settings.LENGUAJE_DEFECTO)
    # relation: sólo se incluirá en los metados del documento en el repositorio
    # TODO: Consultar sobre identifier, URI

    # campos internos
    alfresco_uuid = models.CharField(max_length=36, validators=[validators.UUIDValidator])

    class Meta:
        abstract = True
        permissions = (
            ('puede_archivar', u'Puede revisar y archivar un trabajo'),
        )

    def __unicode__(self):
        return self.title

    def pretty_language(self):
        return [value for key, value in settings.LENGUAJE_SELECCION if key == self.language][0]

    def save_to_alfresco(self, cml, parent_uuid = None, force_insert=False, force_update=False):
        if force_insert and force_update:
            raise ValueError("Cannot force both insert and updating in model saving.")

        if not self.alfresco_properties:
            self.get_alfresco_properties()

        properties = Contenido.resolve_alfresco_prefixes(self.alfresco_properties)

	if force_update or not force_insert and self.alfresco_uuid:
            return cml.update(self.alfresco_uuid, properties)
        else:
            if parent_uuid is None:
                raise TypeError("No se puede pasar None como UUID del padre si el contenido debe ser creado.")
            def create_callback(result):
                self.alfresco_uuid = result.destination.uuid
            return cml.create(parent_uuid,
                settings.ALFRESCO_PFC_MODEL_NAMESPACE % 'contenido', properties,
                create_callback)

    def _get_alfresco_properties(self):
        return {
            'cm:name': self.title,
            'cm:title': self.title,
            'cm:format': self.format,
            'cm:description': self.description,
            # TODO; Modificar el modelo en Alfresco para que type pueda ser multivaluado
            'cm:type': settings.TIPO_DOCUMENTO_TO_DUBLIN_CORE[self.type][-1],
            'cm:language': self.language,
            'cm:publisher': settings.PUBLISHER_DEFECTO
        }


class Trabajo(Contenido):
    """Modelo principal de un trabajo."""
    
    ESTADO_SELECCION = (
        ('solicitado', u'Solicitada la defensa'),
        ('rechazado',  u'Rechazado'),
        ('autorizado', u'Autorizado'),
        ('calificado', u'Calificado'),
        ('archivado',  u'Archivado'),
    )

    # dublin core
    type = models.CharField(max_length=30, choices=settings.TIPO_DOCUMENTO_TRABAJO_SELECCION)
    creator_nombre = models.CharField(max_length=50, verbose_name= u'nombre del autor')
    creator_apellidos = models.CharField(max_length=50, verbose_name= u'apellidos del autor')
    creator_email = models.EmailField(max_length=50,
                                      verbose_name = u'correo electrónico del autor',
                                      validators=[validators.EmailCreatorValidator])
    # pfc
    niu = models.CharField(max_length=10, verbose_name=u"NIU", validators=[validators.NIUValidator])
    titulacion = models.ForeignKey(Titulacion, verbose_name=u"titulación")
    tutor_nombre = models.CharField(max_length=50, verbose_name=u'nombre del tutor')
    tutor_apellidos = models.CharField(max_length=50, verbose_name=u'apellidos del tutor')
    tutor_email = models.EmailField(max_length=50,
                                    verbose_name=u'correo electrónico del tutor',
                                    validators=[validators.EmailTutorValidator],
                                    db_index=True)
    director_nombre = models.CharField(max_length=50, blank=True, null=True,
                                       verbose_name=u'nombre del director')
    director_apellidos = models.CharField(max_length=50, blank=True, null=True,
                                          verbose_name=u'apellidos del director')
 
    #calificado
    fecha_defensa = models.DateField(verbose_name=u"fecha defensa", blank=True, null=True)
    calificacion_numerica = models.DecimalField(max_digits=3, decimal_places=1, verbose_name=u"calificación numérica", blank=True, null=True)
    calificacion = models.CharField(max_length=30, choices=settings.CALIFICACION_SELECCION, verbose_name=u"calificación", blank=True, null=True)
    modalidad = models.CharField(max_length=50, choices=settings.MODALIDAD_SELECCION, default=settings.MODALIDAD_DEFECTO, blank=True, null=True)
    tribunal_presidente_nombre = models.CharField(max_length=50, blank=True, null=True)
    tribunal_presidente_apellidos = models.CharField(max_length=50, blank=True, null=True)
    tribunal_secretario_nombre = models.CharField(max_length=50, blank=True, null=True)
    tribunal_secretario_apellidos = models.CharField(max_length=50, blank=True, null=True)  
 
    #archivado
    subject = models.CharField(max_length=30, verbose_name=u"tema", blank=True, null=True)
    rights = models.CharField(max_length=200, choices=settings.DERECHOS_SELECCION, verbose_name=u"derechos", blank=True, null=True)
    coverage = models.CharField(max_length=200, verbose_name=u"cobertura", blank=True, null=True)    

    # internos
    fecha_subido = models.DateField(auto_now_add = True)
    estado = models.CharField(max_length=20,
                              choices=ESTADO_SELECCION,
                              db_index=True)

    def __getattr__(self, name):
        parts = name.rsplit('_')
        if len(parts) > 2 and parts[-1] == 'completo':
            campo_nombre = '_'.join(parts[0:-1])
            campo_apellidos = '_'.join(parts[0:-2] + ['apellidos'])
            if campo_nombre in self.__dict__ and campo_apellidos in self.__dict__:
                if self.__dict__[campo_nombre] and self.__dict__[campo_apellidos]:
                    def nombre_completo():
		        if (self.__dict__[campo_nombre] == None or self.__dict__[campo_apellidos] == None):
			  return none
			else:
			  return settings.NOMBRE_COMPLETO_PLANTILLA % {
			      'nombre': self.__dict__[campo_nombre],
			      'apellidos': self.__dict__[campo_apellidos],
			  }
                else:
                    def nombre_completo():
                        return None

tfc_webapps/defensa/templates/anexo_editar.html
<div class="item">
    <form action="." enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <table>
            <tr>
                <th><label for="id_title">Título (*):</label><br/>
                    <small>(máx. 200 caracteres)</small></th>
                <td>{{ form.title.errors }}{{ form.title }}</td>
            </tr>
            <tr>
                <th><label for="id_description">Descripción (*):</label><br/>
                    <small>(máx. 1000 caracteres)</small></th>
                <td>{{ form.description.errors }}{{ form.description }}</td>
            </tr>
            <tr>
                <th><label for="id_language">Idioma (*):</label></th>
                <td>{{ form.language.errors }}{{ form.language }}</td>
            </tr>
            <tr>
                <th><label for="id_type">Tipo (*):</label></th>
                <td>{{ form.type.errors }}{{ form.type }}</td>
            </tr>
        </table>
</form>
</div>

tfc_webapps/defensa/templates/calificar_trabajo.html
{% extends "solicitud_mostrar.html" %}

{% block extra_head %}
<script language="javascript" src="{{ STATIC_URL }}js/jquery-1.6.3.min.js"></script>
<script language="javascript" src="{{ STATIC_URL }}js/jquery-ui-1.8.16.custom.min.js"></script>
<script language="javascript" src="{{ STATIC_URL }}js/jquery.ui.datepicker-es.js"></script>
<script type="text/javascript">
    $(function() {
        $.datepicker.setDefaults($.datepicker.regional["es"]);
        $( "#id_fecha_defensa" ).datepicker({
                showOn: "both",
                buttonImage: "{{ STATIC_URL }}images/calendar.png",
                buttonImageOnly: true
            });
        });
</script>
{% endblock %}

{% block estado_proxima_accion %}
{% endblock %}

{% block anexos %}
{% endblock %}

{% block content_title %}Calificar Trabajo Fin de Carrera{% endblock %}

{% block messages %}
<div class="info">
    <h3>Calificación</h3>
    <p>
    Por favor, rellene el formulario al final de la página con los  datos referentes
    a la defensa del trabajo fin de carrera y haga <em>clic</em> en el botón
    <em>Calificar</em> para remitir dicha información. Tenga en cuenta que este
    procedimiento debe ser realizado una vez haya tenido lugar la defensa del trabajo
    frente al tribunal.</p>
</div>
{% endblock %}

{% block accion_formulario %}
<form id="form" action="." enctype="multipart/form-data" method="POST">
{% csrf_token %}
<div class="item">
    <h3>Calificación</h3>
    {{ f.non_field_errors }}
    <table>
        <tr>
            <th><label for="id_calificacion_numerica">Calificacion numerica (*):</label></th>
            <td>{{ f.calificacion_numerica.errors }}{{ f.calificacion_numerica }}</td>
        </tr>
        <tr>
            <th><label for="id_calificacion">Calificacion (*):</label></th>
            <td>{{ f.calificacion.errors }}{{ f.calificacion }}</td>
        </tr>
        <tr>
           <th><label for="id_fecha_defensa">Fecha de la defensa (*):</label></th>
           <td>{{ f.fecha_defensa.errors }}{{ f.fecha_defensa }}</td>
        </tr>
    </table>

    <h3>Presidente del tribunal</h3>
    <p><small>Presidente del tribunal encargado de la evaluación del trabajo.</small></p>
    <table>
        <tr>
           <th><label for="id_tribunal_presidente_nombre">Nombre (*):</label></th>
           <td>{{ f.tribunal_presidente_nombre.errors }}{{ f.tribunal_presidente_nombre }}</td>
        </tr>
        <tr>
            <th><label for="id_calificacion_numerica">Apellidos (*):</label></th>
            <td>{{ f.tribunal_presidente_apellidos.errors }}{{ f.tribunal_presidente_apellidos }}</td>
        </tr>
    </table>

    <h3>Secretario del tribunal</h3>
    <p><small>Secretario del tribunal encargado de la evaluación del trabajo.</small></p>
    <table>
        <tr>
           <th><label for="id_tribunal_secretario_nombre">Nombre (*):</label></th>
           <td>{{ f.tribunal_secretario_nombre.errors }}{{ f.tribunal_secretario_nombre }}</td>
        </tr>
        <tr>
            <th><label for="id_tribunal_secretario_apellidos">Apellidos (*):</label></th>
            <td>{{ f.tribunal_secretario_apellidos.errors }}{{ f.tribunal_secretario_apellidos }}</td>
        </tr>
    </table>

    {% for form in v.forms %}
    {% if v.forms|length == 1 %}
    <h3>Vocal del tribunal</h3>
    <p><small>Vocal del tribunal encargado de la evaluación del trabajo.</small></p>
    {% else %}
    <h3>Vocal {{ forloop.counter }} del tribunal</h3>
    <p><small>Vocal {{ forloop.counter }} del tribunal encargado de la evaluación del trabajo.</small></p>
    {% endif %}
    {{ v.management_form }}
    {{ form.non_field_errors }}
	<table>
            <tr>
                <th><label for="id_tribunalvocal_set-{{ forloop.counter0 }}-nombre">Nombre (*):</label></th>
                <td>{{ form.nombre.errors }}{{ form.nombre }}</td>
            </tr>
            <tr>
                <th><label for="id_tribunalvocal_set-{{ forloop.counter0 }}-apellidos">Apellidos (*):</label></th>
                <td>{{ form.apellidos.errors }}{{ form.apellidos }}</td>
            </tr>
	</table>
    {% endfor %}
    <br/>
    <input type="submit" class="button" value="Calificar" />
</div>
</form>
{% endblock %}

tfc_webapps/defensa/templates/index.html
{% extends "base.html" %}

tfc_webapps/defensa/templates/licencia.html
{% if license_url %}<a rel="license" href="{{ license_url }}" title="{{ license_text }}">{% endif %}{% if license_image %}<img title="{{ license_text }}" alt="{{ license_text }}" style="border-width:0; vertical-align:middle;" src="{{ license_image }}" />{% endif %}{% if not license_image %}{{ license_text }}{% endif %}{% if license_url %}</a>{% endif %}

tfc_webapps/defensa/templates/solicitar_defensa.html
{% extends "base.html" %}

{% block extra_head %}
<script language="javascript" src="{{ STATIC_URL }}js/jquery-1.6.3.min.js"></script>
<script language="javascript" src="{{ STATIC_URL }}js/jquery-ui-1.8.16.custom.min.js"></script>
<script language="javascript" src="{{ STATIC_URL }}js/jquery.chainedSelect.min.js"></script>
<script language="javascript" src="{{ STATIC_URL }}js/tabbed_formset.min.js"></script>
<script language="javascript" src="{{ STATIC_URL }}js/defensa.js"></script>
<script type="text/javascript">
    $(function() {
        solicitud.initForm("#tabs", {
            anexoFormsetPrefix: "{{ a.prefix }}",
            anexoNo: {{ a|length }},
            anexoFormTemplate: "#anexo-empty-form",
            anexoAddButton: "#add_tab",
            anexoRemoveButton: "#tabs span.ui-icon-close",
        });
        $('#id_titulacion').chainedSelect({
            parent: '#id_centro',
            url: '/defensa/titulacion/find-by-centro/',
            value: 'id',
            label: 'nombre',
            preloadUrl: '{{ STATIC_URL }}images/busy.gif'
        });
    })
</script>
{% endblock %}

{% block content_title %}Solicitud de defensa de Trabajo Fin de Carrera{% endblock %}
{% block content %}
<div class=item>
<p>Va a solicitar la defensa de su proyecto fin de carrera. Por favor, selecciones el archivo
que contiene el documento de la memoria y rellene los campos del formulario. Si lo desea,
puede utilizar el botón <em>Añadir anexo</em> para adjuntar documentación o recursos
adicionales. Cuando haya terminado, haga <em>clic</em> en el botón <em>Enviar</em>.</p>
<br/>
<button id="add_tab">Añadir anexo</button>
<form id="form" action="." enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <div id="tabs">
        <ul>
            <li><a href="#tabs-trabajo">Memoria</a></li>
	    {% for form in a %}
	    <li><a href="#tabs-{{ a.prefix }}-{{ forloop.counter0 }}">Anexo {{ forloop.counter }}</a> <span class='ui-icon ui-icon-close'>Eliminar anexo</span></li>
	    {% endfor %}
        </ul>

        <div id="tabs-trabajo">
            {{ f.non_field_errors }}
            <table>
                <tr>
                    <th><label for="id_file">Documento de la memoria (*):</label></th>
                    <td>{{ f.file.errors }}{{ f.file }}{{ f.filename }}{{ f.fileid }}</td>
                </tr>
                <tr>
                    <th><label for="id_title">Título (*):</label><br/>
                        <small>(máx. 200 caracteres)</small></th>
                    <td>{{ f.title.errors }}{{ f.title }}</td>
                </tr>
                <tr>
                    <th><label for="id_description">Descripción (*):</label><br/>
                        <small>(máx. 1000 caracteres)</small></th>
                    <td>{{ f.description.errors }}{{ f.description }}</td>
                </tr>
                <tr>
                    <th><label for="id_language">Idioma (*):</label></th>
                    <td>{{ f.language.errors }}{{ f.language }}</td>
                </tr>
            </table>
            <div class="line"></div>

            <h3>Autor</h3>
            <table>
                <tr>
                    <th><label for="id_creator_nombre">Nombre (*):</label></th>
                    <td>{{ f.creator_nombre.errors }}{{ f.creator_nombre }}</td>
                </tr>
                <tr>
                    <th><label for="id_creator_apellidos">Apellidos (*):</label><br/>
                        <small>(indicar ambos apellidos)</small></th>
                    <td>{{ f.creator_apellidos.errors }}{{ f.creator_apellidos }}</td>
                </tr>
                <tr>
                    <th><label for="id_niu">NIU (*):</label></th>
                    <td>{{ f.niu.errors }}{{ f.niu }}</td>
                </tr>
                <tr>
                    <th><label for="id_centro">Centro (*):</label></th>
                    <td>{{ f.centro.errors }}{{ f.centro }}</td>
                </tr>
                <tr>
                    <th><label for="id_titulacion">Titulación (*):</label></th>
                    <td>{{ f.titulacion.errors }}{{ f.titulacion }}</td>
                </tr>
            </table>
            <div class="line"></div>

            <h3>Tutor académico</h3>
            <p><small>Tutor académico del trabajo vinculado a la Universidad.</small></p>
            <table>
                <tr>
                    <th><label for="id_tutor_nombre">Nombre (*):</label></th>
                    <td>{{ f.tutor_nombre.errors }}{{ f.tutor_nombre }}</td>
                </tr>
                <tr>
                    <th><label for="id_tutor_apellidos">Apellidos (*):</label></th>
                    <td>{{ f.tutor_apellidos.errors }}{{ f.tutor_apellidos }}</td>
                </tr>
                <tr>
                    <th><label for="id_tutor_email">Correo electrónico (*):</label></th>
                    <td>
                        {{ f.tutor_email.errors }}
                        {{ f.tutor_email }}
                        @{{ dominio_correo_tutor }}
                    </td>
                </tr>
            </table>
            <div class="line"></div>

            <h3>Director (opcional)</h3>
            <p><small>Director no académico del trabajo, generalmente externo a la
            Universidad y vinculado a una empresa.</small></P>
            <table>
                <tr>
                    <th><label for="id_director_nombre">Nombre:</label></th>
                    <td>{{ f.director_nombre.errors }}{{ f.director_nombre }}</td>
                </tr>
                <tr>
                    <th><label for="id_director_apellidos">Apellidos:</label></th>
                    <td>{{ f.director_apellidos.errors }}{{ f.director_apellidos }}</td>
                </tr>
            </table>
        </div>

	{% for form in a %}
	<div id="tabs-{{ a.prefix }}-{{ forloop.counter0 }}">
            {{ form.non_field_errors }}
	    <table>
                <tr>
                    <th><label for="id_file">Documento del anexo (*):</label></th>
                    <td>{{ form.file.errors }}{{ form.file }}{{ form.filename }}{{ form.fileid }}</td>
                </tr>
                <tr>
                    <th><label for="id_anexo_set-{{ forloop.counter0 }}-title">Título (*):</label><br/>
                        (máx. 200 caracteres)</th>
                    <td>{{ form.title.errors }}{{ form.title }}</td>
                </tr>
                <tr>
                    <th><label for="id_anexo_set-{{ forloop.counter0 }}-description">Descripción (*):</label><br/>
                        (máx. 1000 caracteres)</th>
                    <td>{{ form.description.errors }}{{ form.description }}</td>
                </tr>
                <tr>
                    <th><label for="id_anexo_set-{{ forloop.counter0 }}-language">Idioma (*):</label></th>
                    <td>{{ form.language.errors }}{{ form.language }}</td>
                </tr>
                <tr>
                    <th><label for="id_anexo_set-{{ forloop.counter0 }}-type">Tipo (*):</label></th>
                    <td>{{ form.type.errors }}{{ form.type }}</td>
                </tr>
	    </table>
            <label for="id_anexo_set-{{ forloop.counter0 }}-DELETE">Eliminar:</label>
            {{ form.DELETE }}
	</div>
	{% endfor %}
    </div>

    {% with a.empty_form as form %}
    <div id="anexo-empty-form">
        {{ form.non_field_errors }}
        <table>
            <tr>
                <th><label for="id_file">Documento del anexo (*):</label></th>
                <td>{{ form.file.errors }}{{ form.file }}</td>
            </tr>
            <tr>
                <th><label for="id_anexo_set-__prefix__-title">Título (*):</label><br/>
                    <small>(máx. 200 caracteres)</small></th>
                <td>{{ form.title.errors }}{{ form.title }}</td>
            </tr>
            <tr>
                <th><label for="id_anexo_set-__prefix__-description">Descripción (*):</label><br/>
                    <small>(máx. 1000 caracteres)</small></th>
                <td>{{ form.description.errors }}{{ form.description }}</td>
            </tr>
            <tr>
                <th><label for="id_anexo_set-__prefix__-language">Idioma (*):</label></th>
                <td>{{ form.language.errors }}{{ form.language }}</td>
            </tr>
            <tr>
                <th><label for="id_anexo_set-__prefix__-type">Tipo (*):</label></th>
                <td>{{ form.type.errors }}{{ form.type }}</td>
            </tr>
        </table>
        <label for="id_anexo_set-__prefix__-DELETE">Eliminar:</label>
        {{ form.DELETE }}
    </div>
    {% endwith %}

    {{ a.management_form }}
    <input type="submit" class="button" value="Enviar" />
</form>
</div>
{% endblock %}

tfc_webapps/defensa/templates/trabajo_editar.html
<div class="item">
    <form action="." enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <table>
            <tr>
                <th><label for="id_title">Título (*):</label><br/>
                    <small>(máx. 200 caracteres)</small></th>
                <td>{{ form.title.errors }}{{ form.title }}</td>
            </tr>
            <tr>
                <th><label for="id_description">Descripción (*):</label><br/>
                    <small>(máx. 1000 caracteres)</small></th>
                <td>{{ form.description.errors }}{{ form.description }}</td>
            </tr>
            <tr>
                <th><label for="id_language">Idioma (*):</label></th>
                <td>{{ form.language.errors }}{{ form.language }}</td>
            </tr>
        </table>
    </form>
</div>