trunk/tfc_webapps/subirproyectos/urls.py
from django.conf.urls.defaults import *
from django.core.urlresolvers import reverse

from subirproyectos import models

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('subirproyectos.views',
    url(r'^/$', 'index'),
    url(r'^/titulacion/find-by-centro/$', 'filter', {
        'model_class': models.Titulacion,
        'field_name': 'centro',
    }),
    url(r'^/solicitar/$', 'solicitar_defensa'),
    url(r'^/(?P<id>\d+)/$', 'solicitud_mostrar', name='proyecto_view'),
    url(r'^/(?P<id>\d+)/contenido/$', 'descargar_contenido'),
    url(r'^/(?P<id>\d+)/anexo/(?P<anexo_id>\d+)/$', 'descargar_anexo', name='anexo_view'),
    url(r'^/(?P<id>\d+)/autorizar/$', 'autorizar_defensa'),
    url(r'^/(?P<id>\d+)/calificar/$', 'calificar_proyecto'),
    url(r'^/(?P<id>\d+)/archivar/$', 'archivar_proyecto'),
    url(r'^/autorizar/$', 'lista_autorizar'),
    url(r'^/calificar/$', 'lista_calificar'),
    url(r'^/archivar/$', 'lista_archivar'),
)

trunk/tfc_webapps/subirproyectos/models.py
# -*- coding: utf-8 -*-

from django.core.validators import MaxLengthValidator
from django.db import models
from django.contrib import auth

from subirproyectos import settings, validators
from subirproyectos.alfresco import Alfresco

from datetime import date

import os
import re


class AlfrescoPFCModel(models.Model):
    NAMESPACES = Alfresco.NAMESPACES
    NAMESPACES['pfc'] = settings.ALFRESCO_PFC_MODEL_NAMESPACE 

    class Meta:
        abstract = True

    def get_alfresco_properties(self):
        properties = self._get_alfresco_properties()
        items = list(properties.items())
        for i, item in enumerate(items):
            (namespace, sep, name) = item[0].partition(':')
            if sep and namespace in self.NAMESPACES:
                items[i] = (self.NAMESPACES[namespace] % name, item[1])
        return dict(items)

    def _get_alfresco_properties(self):
        return {}


class Centro(AlfrescoPFCModel):
    nombre = models.CharField(max_length=200)
    codigo_centro = models.CharField(max_length=200)
    alfresco_uuid = models.CharField(max_length=36, blank = 'true', null = 'true', validators=[validators.UUIDValidator])

    def __unicode__(self):
        return self.nombre
    
    def _get_alfresco_properties(self):
        return {
            'cm:name': self.nombre,
	    'pfc:codigoCentro' : self.codigo_centro,
    }    


class Titulacion(AlfrescoPFCModel):
    nombre = models.CharField(max_length=200)
    centro = models.ForeignKey(Centro)
    codigo_plan = models.CharField(max_length=200)
    anyo_comienzo_plan = models.IntegerField()
    titulacion_vigente = models.BooleanField()
    alfresco_uuid = models.CharField(max_length=36, blank = 'true', null = 'true', validators=[validators.UUIDValidator])

    def __unicode__(self):
        return self.nombre

    def _get_alfresco_properties(self):
        return {
            'cm:name': self.nombre,
	    'pfc:codigoPlan' : self.codigo_plan,
	    'pfc:anyoComienzoPlan' : self.anyo_comienzo_plan,
	    'pfc:titulacionVigente' : self.titulacion_vigente
        }    


class Contenido(AlfrescoPFCModel):
    # dublin core
    title = models.CharField(max_length=200, verbose_name="título")
    format = models.CharField(max_length=30, choices=settings.FORMATO_SELECCION)
    description = models.TextField(verbose_name="descripción", validators=[MaxLengthValidator(1000)])
    type = models.CharField(max_length=30, choices=settings.TIPO_DOCUMENTO_SELECCION, default=settings.TIPO_DOCUMENTO_DEFECTO)
    language = models.CharField(max_length=2, choices=settings.LENGUAJE_SELECCION, verbose_name="idioma", default=settings.LENGUAJE_DEFECTO)
    # relation: sólo se incluirá en los metados del documento en el repositorio
    # TODO: Consultar sobre publisher, identifier, URI

    # internos
    alfresco_uuid = models.CharField(max_length=36, validators=[validators.UUIDValidator])

    class Meta:
        abstract = True
        permissions = (
            ('puede_archivar', 'Puede revisar y archivar un trabajo'),
        )

    def __unicode__(self):
        return self.title

    def type_detallado(self):
        return [value for key, value in settings.TIPO_DOCUMENTO_SELECCION if key == self.type][0]

    def language_detallado(self):
        return [value for key, value in settings.LENGUAJE_SELECCION if key == self.language][0]

    def save_to_alfresco(self, parent_uuid, cml, force_insert=False, force_update=False):
        if force_insert and force_update:
            raise ValueError("Cannot force both insert and updating in model saving.")

	if force_update or not force_insert and self.alfresco_uuid:
            return cml.update(self.alfresco_uuid,
                self.get_alfresco_properties())
        else:
            def create_callback(result):
                self.alfresco_uuid = result.destination.uuid
            return cml.create(parent_uuid,
                settings.ALFRESCO_PFC_MODEL_NAMESPACE % 'contenido',
                self.get_alfresco_properties(), create_callback)

    def _get_alfresco_properties(self):
        return {
            'cm:name': self.title,
            'cm:title': self.title,
            'cm:format': self.format,
            'cm:description': self.description,
            'cm:type': self.type,
            'cm:language': self.language,
        }


class Proyecto(Contenido):
    ESTADO_SELECCION = (
        ('solicitado', 'Solicitada la defensa'),
        ('rechazado',  'Rechazado'),
        ('autorizado', 'Autorizado'),
        ('calificado', 'Calificado'),
        ('archivado',  'Archivado'),
    )

    # dublin core
    creator_nombre = models.CharField(max_length=50, verbose_name= 'nombre del autor')
    creator_apellidos = models.CharField(max_length=50, verbose_name= 'apellidos del autor')
    creator_email = models.EmailField(max_length=50,
                                      verbose_name = 'correo electrónico del autor',
                                      validators=[validators.EmailCreatorValidator])
    # pfc
    niu = models.CharField(max_length=10, verbose_name="NIU", validators=[validators.NIUValidator])
    titulacion = models.ForeignKey(Titulacion, verbose_name="titulación")
    tutor_nombre = models.CharField(max_length=50, verbose_name='nombre del tutor')
    tutor_apellidos = models.CharField(max_length=50, verbose_name='apellidos del tutor')
    tutor_email = models.EmailField(max_length=50,
                                    verbose_name='correo electrónico del tutor',
                                    validators=[validators.EmailTutorValidator],
                                    db_index=True)
    director_nombre = models.CharField(max_length=50, blank=True, null=True,
                                       verbose_name='nombre del director')
    director_apellidos = models.CharField(max_length=50, blank=True, null=True,
                                          verbose_name='apellidos del director')
 
    #calificado
    fecha_defensa = models.DateField(default=date.today(), verbose_name="fecha defensa", blank=True, null=True)
    calificacion_numerica = models.DecimalField(max_digits=3, decimal_places=1, verbose_name="calificación numérica", blank=True, null=True)
    calificacion = models.CharField(max_length=30, choices=settings.CALIFICACION_SELECCION, verbose_name="calificación", blank=True, null=True)
    modalidad = models.CharField(max_length=30, blank=True, null=True) # TODO: Añadir selector de modalidad
    tribunal_presidente_nombre = models.CharField(max_length=50, blank=True, null=True)
    tribunal_presidente_apellidos = models.CharField(max_length=50, blank=True, null=True)
    tribunal_secretario_nombre = models.CharField(max_length=50, blank=True, null=True)
    tribunal_secretario_apellidos = models.CharField(max_length=50, blank=True, null=True)  
 
    #archivado
    subject = models.CharField(max_length=30, verbose_name="tema", blank=True, null=True)
    rights = models.CharField(max_length=200, choices=settings.DERECHOS_SELECCION, verbose_name="derechos", blank=True, null=True)
    coverage = models.CharField(max_length=200, verbose_name="cobertura", blank=True, null=True)    

    # internos
    fecha_subido = models.DateField(auto_now_add = True)
    estado = models.CharField(max_length=20,
                              choices=ESTADO_SELECCION,
                              db_index=True)

    def __getattr__(self, name):
        parts = name.rsplit('_')
        if len(parts) > 2 and parts[-1] == 'completo':
            campo_nombre = '_'.join(parts[0:-1])
            campo_apellidos = '_'.join(parts[0:-2] + ['apellidos'])
            if campo_nombre in self.__dict__ and campo_apellidos in self.__dict__:
                if self.__dict__[campo_nombre] and self.__dict__[campo_apellidos]:
                    def nombre_completo():
                        return settings.PLANTILLA_NOMBRE_COMPLETO % {
                            'nombre': self.__dict__[campo_nombre],
                            'apellidos': self.__dict__[campo_apellidos],
                        }
                else:
                    def nombre_completo():
                        return None
                return nombre_completo

        raise AttributeError("%r object has no attribute %r" %
                             (type(self).__name__, name))

    def estado_detallado(self):
        return [value for key, value in self.ESTADO_SELECCION if key == self.estado][0]

    @models.permalink
    def get_absolute_url(self):
        return ('proyecto_view', (), {'id': self.id})

    def _get_alfresco_properties(self):
        properties = super(Proyecto, self)._get_alfresco_properties()
        properties['cm:creator'] = self.creator_nombre_completo()
        properties['pfc:niu'] = self.niu
        properties['pfc:centro'] = self.titulacion.centro.nombre
        properties['pfc:titulacion'] = self.titulacion.nombre
        properties['pfc:tutor'] = self.tutor_nombre_completo()
        properties['pfc:director'] = self.director_nombre_completo()
        properties['pfc:fechaDefensa'] = self.fecha_defensa.isoformat()
        properties['pfc:calificacion'] = self.calificacion
        properties['pfc:calificacionNumerica'] = self.calificacion_numerica
        properties['pfc:modalidad'] = self.modalidad
        properties['pfc:presidenteTribunal'] = self.tutor_nombre_completo()
        properties['pfc:secretarioTribunal'] = self.director_nombre_completo()
        properties['pfc:vocalesTribunal'] = self.tribunal_vocales()
        properties['cm:subject'] = self.subject
        properties['cm:rights'] = settings.TEXTO_DERECHOS[self.rights]
        properties['cm:coverage'] = self.coverage        
        return properties
        
    def tribunal_vocales(self):
        return [vocal.nombre_completo() for vocal in
            TribunalVocal.objects.filter(proyecto_calificado=self.pk).all()]


class TribunalVocal(models.Model):
    proyecto_calificado = models.ForeignKey(Proyecto)

trunk/tfc_webapps/subirproyectos/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.forms.models import inlineformset_factory, BaseInlineFormSet

from subirproyectos import settings, models, validators


def calificacion_valida(calificacion_numerica, calificacion):
    # comprobar calificación y nota numérica
    if calificacion_numerica >= 0.0 and calificacion_numerica <= 4.9:
        if calificacion != 'suspenso':
            return False
    if calificacion_numerica >= 5.0 and calificacion_numerica <= 6.9:
        if calificacion != 'aprobado':
            return False
    if calificacion_numerica >= 7.0 and calificacion_numerica <= 8.9:
        if calificacion != 'notable':
            return False
    if calificacion_numerica >= 9.0 and calificacion_numerica <= 10.0:
        if calificacion not in ('sobresaliente', 'matricula'):
            return False

    return True


class FormularioProyectoBase(forms.ModelForm):
    class Meta:
        model = models.Proyecto

    def append_field_error(self, field, error):
        if field not in self._errors:
            self._errors[field] = forms.util.ErrorList()
        self._errors[field].append(error)

    def append_non_field_error(self, error):
        self.set_error(forms.NON_FIELD_ERRORS, error)


class FormularioProyecto(FormularioProyectoBase):
    DOMINIO_CORREO_TUTOR = '@' + settings.DOMINIO_CORREO_TUTOR

    centro = forms.ModelChoiceField(label="Centro", queryset=models.Centro.objects)
    titulacion = forms.ModelChoiceField(label="Titulación", queryset=models.Titulacion.objects)
    file = forms.FileField(label="Documento de la memoria", validators=[validators.file_format])

    # Sobreescribimos el campo 'tutor_email' para que la comprobación de
    # correo electrónico valido no se haga en el campo del formulario (antes
    # de clean_tutor_email) sino en el campo del modelo
    # (después de clean_tutor_email)
    tutor_email = forms.CharField(max_length=(50 - len(DOMINIO_CORREO_TUTOR)),
                                  label='Correo electrónico del tutor')

    class Meta:
        model = models.Proyecto
	fields = ('title', 'description', 'language', 'file', 'creator_nombre',
            'creator_apellidos', 'niu', 'centro', 'titulacion', 'tutor_nombre',
            'tutor_apellidos', 'tutor_email', 'director_nombre', 'director_apellidos')
        widgets = {
            'title': forms.Textarea(attrs={'cols': 40, 'rows': 3}),
        }

    def clean(self):
        data = self.cleaned_data

        # comprobar nombre y apellidos del director
        if data['director_apellidos'] and not data['director_nombre']:
            self.append_field_error('director_nombre', """
                Si desea indicar un director debe proporcionar tanto el
                nombre como los apellidos.""")
        if data['director_nombre'] and not data['director_apellidos']:
            self.append_field_error('director_apellidos', """
                Si desea indicar un director debe proporcionar tanto el
                nombre como los apellidos.""")

        return data

    def clean_tutor_email(self):
        return self.cleaned_data['tutor_email'] + self.DOMINIO_CORREO_TUTOR


class FormularioAnexoFormset(BaseInlineFormSet):

    def add_fields(self, form, index):
	super(FormularioAnexoFormset, self).add_fields(form, index)
	form.fields["file"] = forms.FileField(validators=[validators.file_format])
        form.fields['title'].widget = forms.Textarea(attrs={'cols': 40, 'rows': 3})

AnexoFormSet = inlineformset_factory(models.Proyecto, models.Anexo,
	formset = FormularioAnexoFormset,
        fields = ('title', 'description', 'language', 'type' ),
	extra = 0)


class FormularioAutorizar(forms.ModelForm):
    comentario = forms.CharField(label="Comentario", max_length=500, required=False,
        widget=forms.Textarea(attrs={'cols': 80, 'rows': 5}))

    class Meta:
        model = models.Proyecto
        fields = ('tutor_nombre', 'tutor_apellidos', 'director_nombre',
            'director_apellidos')


class FormularioProyectoCalificado(FormularioProyectoBase):
    def __init__(self, *args, **kwargs):
	super(FormularioProyectoCalificado, self).__init__(*args, **kwargs)
        self.fields['fecha_defensa'].required = True
        self.fields['calificacion_numerica'].required = True
        self.fields['calificacion'].required = True
        self.fields['modalidad'].required = True
        self.fields['tribunal_presidente_nombre'].required = True
        self.fields['tribunal_presidente_apellidos'].required = True
        self.fields['tribunal_secretario_nombre'].required = True
        self.fields['tribunal_secretario_apellidos'].required = True

    class Meta:
	model = models.Proyecto
	fields = ('fecha_defensa', 'calificacion_numerica', 'calificacion',
            'modalidad', 'tribunal_presidente_nombre',
            'tribunal_presidente_apellidos', 'tribunal_secretario_nombre',
            'tribunal_secretario_apellidos')

    def clean(self):
        data = self.cleaned_data

        if not calificacion_valida(data['calificacion_numerica'], data['calificacion']):
            self.append_field_error('calificacion',
                u"La calificación y la nota numérica no coinciden")

        return data

VocalesFormSet = inlineformset_factory(models.Proyecto, models.TribunalVocal, extra=1)    


class FormularioProyectoArchivado(forms.ModelForm):
    def __init__(self, *args, **kwargs):
	super(FormularioProyectoArchivado, self).__init__(*args, **kwargs)
	#duda, los que no son nullables?
        self.fields['rights'].required = True      
        self.fields['coverage'].required = True    
        self.fields['subject'].required = True               

    class Meta:
	model = models.Proyecto
	fields = ('title', 'creator_nombre', 'creator_apellidos',
            'description', 'language', 'subject',  'rights', 'coverage')

trunk/tfc_webapps/subirproyectos/templates/archivar_proyecto_biblioteca.html
<html>

<head>
<tittle>Mostrando datos a validar</tittle>
</head>

<body>


<!--<form action="/subirproyectos/validar_biblioteca/" method="post" enctype="multipart/form-data">
{% csrf_token %}-->

<!--Creador: <input type="text" name="creator" value="{{p.creator}}" /><br />
Titulo: <input type="text" name="title" value="{{p.title}}" /><br />
Descripcion: <input type="text" name="description" value="{{p.description}}" /><br />
Lenguaje: <input type="text" name="language" value="{{p.language}}" /><br />-->
<!--Formato: <input type="text" name="formato" value="{{p.format}}" /><br />
Relation: <input type="text" name="relation" value="{{p.relation}}" /><br />
Tipo: <input type="text" name="tipo" value="{{p.type}}" /><br />-->

<!--Subject: <input type="text" name="subject"/><br />
Rights <input type="text" name="rigths"/><br />
Coverage <input type="text" name="coverage"/><br />
<input type="hidden" name="id" value="{{p.id}}">
<input type="submit" value="Aceptar" />-->

<div class="item">
    <form action="." enctype="multipart/form-data" method="POST"> 
    {% csrf_token %}
    <table id="proyecto">
    {{ f.as_table }}
    </table>
    <input type="submit" class="button" value="Enviar" />
    </form>
</div>

</body>

</html>

trunk/tfc_webapps/subirproyectos/templates/calificar_proyecto_tutor.html
{% extends "subirproyectos/base.html" %}

{% block extra_head %}
<script language="javascript" src="{{ STATIC_URL }}js/jquery-1.6.3.min.js"></script>
<script language="javascript" src="{{ STATIC_URL }}js/jquery-ui-1.8.16.custom.min.js"></script>
<script language="javascript" src="{{ STATIC_URL }}js/jquery.formset.js"></script>
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/smoothness/jquery-ui-1.8.16.custom.css" />
<script type="text/javascript">
    $(function() {
        $('#proyecto_vocales tbody tr').formset({
             prefix: '{{ v.prefix }}',
             addText: 'añadir',
             deleteText: 'eliminar',
             extraClasses: ['row1', 'row2', 'row3']
        });
        $('#accordion').accordion({
             active: false,
             collapsible: true,
             autoHeight: false,
             animated: false
        });
    })
</script>
{% endblock %}



{% block content_title %}Calificación trabajo de fin de carrera{% endblock %}
{% block content %}
<div class="item">
    <form action="." enctype="multipart/form-data" method="POST"> 
    {% csrf_token %}
    <table id="proyecto">
    {{ f.as_table }}
    </table>
    <div id="accordion">
      <h3><a href="#">Vocales del tribunal</a></h3>
      <div>
        <table id="proyecto_vocales">
          <thead>
            <tr>
              <th scope="col">Nombre vocal</th>
              <th scope="col">Apellidos vocal</th>
            </tr>
          </thead>
          <tbody>
            {% for form in v.forms %}
            <tr id="{{ form.prefix }}-row">
	      <td>{{ form.nombre.errors }}{{ form.nombre }}</td> 
              <td>{{ form.apellidos.errors }}{{ form.apellidos }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table> 
        {{ v.management_form }} 
      </div>
    <input type="submit" class="button" value="Enviar" />
    </form>
</div>
{% endblock %}

trunk/tfc_webapps/subirproyectos/templates/login.html
{% extends "base.html" %}

{% block content_title %}Inicio de Sesión{% endblock %}
{% block content %}
<div class="item">
  <form action="{% url django.contrib.auth.views.login %}" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <table>
      <tr>
        <td>Nombre de Usuario</td>
        <td>{{ form.username }}{{ form.username.errors }}</td>
      </tr>
      <tr>
        <td>Contraseña</td>
        <td>{{ form.password }}{{ form.username.errors }}</td>
      </tr>
    </table>
    <input type="submit" class="button" value="Acceder" />
    <input type="hidden" name="next" value="/subirproyectos/" />
  </form>
</div>
{% endblock %}

trunk/tfc_webapps/subirproyectos/templates/solicitar_defensa.html
{% extends "base.html" %}

{% block extra_head %}
<script language="javascript" src="{{ STATIC_URL }}js/jquery-1.6.3.min.js"></script>
<script language="javascript" src="{{ STATIC_URL }}js/jquery-ui-1.8.16.custom.min.js"></script>
<script language="javascript" src="{{ STATIC_URL }}js/jquery.chainedSelect.min.js"></script>
<script language="javascript" src="{{ STATIC_URL }}js/tabbed_formset.min.js"></script>
<script language="javascript" src="{{ STATIC_URL }}js/proyecto.js"></script>
<script type="text/javascript">
    $(function() {
        proyecto.initForm("#tabs", {
            anexoFormsetPrefix: "{{ a.prefix }}",
            anexoNo: {{ a|length }},
            anexoFormTemplate: "#anexo-empty-form",
            anexoAddButton: "#add_tab",
            anexoRemoveButton: "#tabs span.ui-icon-close",
        });
        $('#id_titulacion').chainedSelect({
            parent: '#id_centro',
            url: '/subirproyectos/titulacion/find-by-centro/',
            value: 'id',
            label: 'nombre',
            preloadUrl: '{{ STATIC_URL }}images/busy.gif'
        });
    })
</script>
{% endblock %}

{% block content_title %}Solicitud de defensa de Trabajo Fin de Carrera{% endblock %}
{% block content %}
<div class=item>

<button id="add_tab">Añadir anexo</button>
<form id="form" action="." enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    <div id="tabs">
        <ul>
            <li><a href="#tabs-proyecto">Proyecto</a></li>
	    {% for form in a %}
	    <li><a href="#tabs-{{ a.prefix }}-{{ forloop.counter0 }}">Anexo {{ forloop.counter }}</a> <span class='ui-icon ui-icon-close'>Eliminar anexo</span></li>
	    {% endfor %}
        </ul>

        <div id="tabs-proyecto">
            {{ f.non_field_errors }}
            <table>
                <tr>
                    <th><label for="id_title">Título (*):</label><br/>
                        <small>(máx. 200 caracteres)</small></th>
                    <td>{{ f.title.errors }}{{ f.title }}</td>
                </tr>
                <tr>
                    <th><label for="id_description">Descripción (*):</label><br/>
                        <small>(máx. 1000 caracteres)</small></th>
                    <td>{{ f.description.errors }}{{ f.description }}</td>
                </tr>
                <tr>
                    <th><label for="id_language">Idioma (*):</label></th>
                    <td>{{ f.language.errors }}{{ f.language }}</td>
                </tr>
                <tr>
                    <th><label for="id_file">Documento de la memoria (*):</label></th>
                    <td>{{ f.file.errors }}{{ f.file }}</td>
                </tr>
            </table>
            <div class="line"></div>

            <h3>Autor</h3>
            <table>
                <tr>
                    <th><label for="id_creator_nombre">Nombre (*):</label></th>
                    <td>{{ f.creator_nombre.errors }}{{ f.creator_nombre }}</td>
                </tr>
                <tr>
                    <th><label for="id_creator_apellidos">Apellidos (*):</label><br/>
                        <small>(indicar ambos apellidos)</small></th>
                    <td>{{ f.creator_apellidos.errors }}{{ f.creator_apellidos }}</td>
                </tr>
                <tr>
                    <th><label for="id_niu">NIU (*):</label></th>
                    <td>{{ f.niu.errors }}{{ f.niu }}</td>
                </tr>
                <tr>
                    <th><label for="id_centro">Centro (*):</label></th>
                    <td>{{ f.centro.errors }}{{ f.centro }}</td>
                </tr>
                <tr>
                    <th><label for="id_titulacion">Titulación (*):</label></th>
                    <td>{{ f.titulacion.errors }}{{ f.titulacion }}</td>
                </tr>
            </table>
            <div class="line"></div>

            <h3>Tutor académico</h3>
            <p><small>Tutor académico del proyecto vinculado a la Universidad.</small></p>
            <table>
                <tr>
                    <th><label for="id_tutor_nombre">Nombre (*):</label></th>
                    <td>{{ f.tutor_nombre.errors }}{{ f.tutor_nombre }}</td>
                </tr>
                <tr>
                    <th><label for="id_tutor_apellidos">Apellidos (*):</label></th>
                    <td>{{ f.tutor_apellidos.errors }}{{ f.tutor_apellidos }}</td>
                </tr>
                <tr>
                    <th><label for="id_tutor_email">Correo electrónico (*):</label></th>
                    <td>
                        {{ f.tutor_email.errors }}
                        {{ f.tutor_email }}
                        @{{ dominio_correo_tutor }}
                    </td>
                </tr>
            </table>
            <div class="line"></div>

            <h3>Director (opcional)</h3>
            <p><small>Director no académico del proyecto, generalmente externo a la
            Universidad y vinculado a una empresa.</small></P>
            <table>
                <tr>
                    <th><label for="id_director_nombre">Nombre:</label></th>
                    <td>{{ f.director_nombre.errors }}{{ f.director_nombre }}</td>
                </tr>
                <tr>
                    <th><label for="id_director_apellidos">Apellidos:</label></th>
                    <td>{{ f.director_apellidos.errors }}{{ f.director_apellidos }}</td>
                </tr>
            </table>
        </div>

	{% for form in a %}
	<div id="tabs-{{ a.prefix }}-{{ forloop.counter0 }}">
            {{ form.non_field_errors }}
	    <table>
                <tr>
                    <th><label for="id_anexo_set-{{ forloop.counter0 }}-title">Título (*):</label><br/>
                        (máx. 200 caracteres)</th>
                    <td>{{ form.title.errors }}{{ form.title }}</td>
                </tr>
                <tr>
                    <th><label for="id_anexo_set-{{ forloop.counter0 }}-description">Descripción (*):</label><br/>
                        (máx. 1000 caracteres)</th>
                    <td>{{ form.description.errors }}{{ form.description }}</td>
                </tr>
                <tr>
                    <th><label for="id_anexo_set-{{ forloop.counter0 }}-language">Idioma (*):</label></th>
                    <td>{{ form.language.errors }}{{ form.language }}</td>
                </tr>
                <tr>
                    <th><label for="id_anexo_set-{{ forloop.counter0 }}-type">Tipo (*):</label></th>
                    <td>{{ form.type.errors }}{{ form.type }}</td>
                </tr>
                <tr>
                    <th><label for="id_anexo_set-{{ forloop.counter0 }}-file">Documento del anexo (*):</label></th>
                    <td>{{ form.file.errors }}{{ form.file }}</td>
                </tr>
	    </table>
            <label for="id_anexo_set-{{ forloop.counter0 }}-DELETE">Eliminar:</label>
            {{ form.DELETE }}
	</div>
	{% endfor %}
    </div>

    {% with a.empty_form as form %}
    <div id="anexo-empty-form">
        {{ form.non_field_errors }}
        <table>
            <tr>
                <th><label for="id_anexo_set-__prefix__-title">Título (*):</label><br/>
                    <small>(máx. 200 caracteres)</small></th>
                <td>{{ form.title.errors }}{{ form.title }}</td>
            </tr>
            <tr>
                <th><label for="id_anexo_set-__prefix__-description">Descripción (*):</label><br/>
                    <small>(máx. 1000 caracteres)</small></th>
                <td>{{ form.description.errors }}{{ form.description }}</td>
            </tr>
            <tr>
                <th><label for="id_anexo_set-__prefix__-language">Idioma (*):</label></th>
                <td>{{ form.language.errors }}{{ form.language }}</td>
            </tr>
            <tr>
                <th><label for="id_anexo_set-__prefix__-type">Tipo (*):</label></th>
                <td>{{ form.type.errors }}{{ form.type }}</td>
            </tr>
            <tr>
                <th><label for="id_anexo_set-__prefix__-file">Documento del anexo (*):</label></th>
                <td>{{ form.file.errors }}{{ form.file }}</td>
            </tr>
        </table>
        <label for="id_anexo_set-__prefix__-DELETE">Eliminar:</label>
        {{ form.DELETE }}
    </div>
    {% endwith %}

    {{ a.management_form }}
    <input type="submit" class="button" value="Enviar" />
</form>
</div>
{% endblock %}